[General]
__userfile__=true

[desktopswitch]
alignment=Left

[mount]
alignment=Right

[panel1]
alignment=-1
animation-duration=0
background-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
background-image=
desktop=0
font-color=@Variant(\0\0\0\x43\0\xff\xff\0\0\0\0\0\0\0\0)
hidable=false
hide-on-overlap=false
iconSize=22
lineCount=1
lockPanel=false
opacity=100
panelSize=38
plugins=fancymenu, spacer, quicklaunch, spacer2, taskbar, desktopswitch, statusnotifier, tray, mount, volume, worldclock, showdesktop
position=Bottom
reserve-space=true
show-delay=0
visible-margin=true
width=100
width-percent=true

[quicklaunch]
apps\1\desktop=/usr/share/applications/pcmanfm-qt.desktop
apps\2\desktop=/usr/share/applications/firefox.desktop
apps\size=2

[spacer]
alignment=Left
expandable=false
size=22
spaceType=invisible
type=spacer

[spacer2]
alignment=Left
size=30
spaceType=invisible
type=spacer

[taskbar]
alignment=Left

[tray]
alignment=Right

[volume]
alignment=Right

[worldclock]
alignment=Right
