style:Estilo:square,round
position:Posición:bottom,top
transparency:Transparencia:false,true
height:Altura:15pt,13pt,18pt,20pt,custom
mode:Mode:solid,underline
rofi_style:Rofi Style:solid,underline
solid_line:Solid Line:true,false
autohide:Autohide:false,true
autohide_delay:Delay Autohide (ms):100,150,200,300,500,custom
autohide_method:Método Autohide:kill,hide
override_redirect:Comportamiento:dock,overlay
transparency_type:Tipo Transparencia:real,pseudo
