style:Estilo:square,round
position:Posición:bottom,top
transparency:Transparencia:true,false
height:Altura:15pt,13pt,18pt,20pt,custom
icon_padding:Icon Padding:1,2,4,6,8,10,12,15,20,custom
autohide:Autohide:false,true
autohide_delay:Delay Autohide (ms):100,150,200,300,500,custom
autohide_method:Método Autohide:kill,hide
override_redirect:Comportamiento:dock,overlay
transparency_type:Tipo Transparencia:real,pseudo
