# Forzar navegación de playlist con la rueda del ratón o botones si el backend falla
MOUSE_BTN7 playlist-next
MOUSE_BTN8 playlist-prev

# Asegurar que las flechas del teclado también lo hagan por si acaso
MBTN_FORWARD playlist-next
MBTN_BACK playlist-prev
