backend = "glx";
vsync = true;
use-damage = true;
unredir-if-possible = true;

shadow = true;

animations = ();

rules = (
  {
    match = "class_i = 'mpv-wallpaper'";
    animations = ();
    shadow = false;
  },
  {
    match = "override_redirect = true && class_i != 'rofi'";
    animations = ();
    shadow = false;
  },
  {
    match = "class_i = 'rofi'";
    animations = (
      { triggers = ["open", "show"]; preset = "appear"; scale = 0.95; duration = 0.15; }
    );
  },
  {
    match = "class_i = 'polybar'";
    shadow = false;
  },
  {
    match = "class_i != 'mpv-wallpaper' && override_redirect = false";
    animations = (
      { triggers = ["open", "show"]; preset = "appear"; scale = 0.95; duration = 0.15; },
      { triggers = ["close", "hide"]; preset = "disappear"; scale = 0.95; duration = 0.12; }
    );
  }
);
