# --- Main Colors ---
background            #0f1416
foreground            #dee3e6
cursor                #dee3e6
cursor_text_color     #0f1416

selection_background  #354a53
selection_foreground  #cfe6f1

url_color             #c4c3eb

# --- ANSI Colors ---
color0                #0f1416
color1                #ffb4ab
color2                #c4c3eb
color3                #b3cad5
color4                #89d0ed
color5                #c4c3eb
color6                #b3cad5
color7                #dee3e6

color8                #40484c
color9                #93000a
color10               #434465
color11               #354a53
color12               #004d61
color13               #354a53
color14               #434465
color15               #c0c8cc

# --- Starship Prompt Bubbles ---
color255              #004d61
color254              #89d0ed
color253              #354a53
color252              #b3cad5
color251              #434465
color250              #c4c3eb
color249              #93000a
color248              #ffb4ab

color232              #b9eaff
color233              #003544
color234              #cfe6f1
color235              #1e333c
color236              #e1e0ff
color237              #2d2d4d
color238              #ffdad6
color239              #690005
color240              #b9eaff

# Matched with unthemed light/dark
color243              #89d0ed
color244              #ffb4ab
color245              #40484c

# --- UI Elements ---
active_tab_foreground   #003544
active_tab_background   #89d0ed
inactive_tab_foreground #b9eaff
inactive_tab_background #004d61

active_border_color     #89d0ed
inactive_border_color   #8a9296

# --- Marks ---
mark1_foreground        #001f29
mark1_background        #b9eaff
mark2_foreground        #071e26
mark2_background        #cfe6f1
mark3_foreground        #181837
mark3_background        #e1e0ff
