#! /bin/bash
# load theme
. ~/.config/rofi/theme
launcher(){
~/.config/rofi/launchers/$theme/launcher.sh
}
powermenu(){
~/.config/rofi/powermenu/$themep/powermenu.sh
}
case "$@" in
	launcher)
	launcher
	;;
	power)
	powermenu
	;;
esac