[colors.primary]
background = '#11140f'
foreground = '#e1e3da'

[colors.cursor]
text = '#11140f'
cursor = '#e1e3da'

[colors.vi_mode_cursor]
text = '#11140f'
cursor = '#a1d582'

[colors.search.matches]
foreground = '#42493d'
background = '#66dac1'

[colors.search.focused_match]
foreground = '#42493d'
background = '#a1d582'

[colors.footer_bar]
foreground = '#42493d'
background = '#e1e3da'

[colors.hints.start]
foreground = '#42493d'
background = '#b7cda6'

[colors.hints.end]
foreground = '#42493d'
background = '#b7cda6'

[colors.selection]
text = '#c2c9b9'
background = '#42493d'


[colors.normal]
black   = '#42493d'
red     = '#ffb4ab'
green   = '#a1d582'
yellow  = '#b7cda6'
blue    = '#66dac1'
magenta = '#a1d582'
cyan    = '#b7cda6'
white   = '#e1e3da'


[colors.bright]
black   = '#8c9384'
red     = '#ffb4ab'
green   = '#a1d582'
yellow  = '#b7cda6'
blue    = '#66dac1'
magenta = '#a1d582'
cyan    = '#b7cda6'
white   = '#e1e3da'


[colors.dim]
black   = '#42493d'
red     = '#ffb4ab'
green   = '#a1d582'
yellow  = '#b7cda6'
blue    = '#66dac1'
magenta = '#a1d582'
cyan    = '#b7cda6'
white   = '#e1e3da'
