[greeter]
indicators = ~host;~spacer;~clock;~spacer;~layout;~session;~a11y;~power
theme-name = Matecito-Dark
icon-theme-name = Tela-dracula-dark
font-name = CozetteVector Bold 10
background = /usr/share/backgrounds/wall-moony-kyouko.png
user-background = false
position = -50%,center

