[vars]
height = 15pt
radius = 0
bottom = true
override-redirect = false
pseudo-transparency = false
background = ${colors.background-solid}
compact-background = ${colors.compact-bar-background}
border-top = 5pt
border-bottom = 5pt
border-left = 0
border-right = 0
line-size = 0pt
comp-modules-hidden = true
font-0 = "JetBrainsMono Nerd Font Mono:style=Bold:size=10;2"
font-1 = "Symbols Nerd Font:size=22;4"
font-2 = "JetBrainsMono Nerd Font Mono:size=10:antialias=false;2"
font-rofi = "Symbols Nerd Font Mono:size=10;2"
font-extra = "JetBrainsMono Nerd Font Mono:size=14;2"
font-symbols = "Symbols Nerd Font Mono:size=10;2"
font-large = "JetBrainsMono Nerd Font Mono:size=12;4"
module-padding = 1
label-padding = 1
icon-padding = 1
focused-bg = ${colors.primary}
focused-fg = ${colors.surface}
focused-underline = 
prefix-bg = ${colors.primary}
prefix-fg = ${colors.surface}
rofi-bg = ${colors.primary}
rofi-fg = ${colors.surface}
rofi-underline = 
rofi-font = 5
launcher-icon =     
launcher-icon-raw = 

; Icon Library
icon-cpu = 
icon-ram = 󰍛
icon-temp = 
icon-date = 󰃭
icon-disk = 󰋊
icon-vol = 󰕾
icon-light = 󰃠
icon-bat = 󱊣
