# Fuente para los titulos de ventanas
font pango:$i3_font 9

set_from_resource $fg i3wm.color7 #f0f0f0
set_from_resource $bg i3wm.color8 #f0f0f0
set_from_resource $bga i3wm.color4  #f0f0f0

# smart_borders on
set $inner_gaps 5
set $outer_gaps 5

gaps inner $inner_gaps
gaps outer $outer_gaps

hide_edge_borders smart

